apiVersion: v1
kind: PersistentVolume
metadata:
  name: dataset-volume
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/dataset"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-volume
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/model"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dataset-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
  volumeName: dataset-volume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
  volumeName: model-volume
