apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage